server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    #db 연결 설정, 및 뷰리졸버 설정
spring:
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations:
      - classpath:/static/
      add-mappings: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: V0QiyiOBlOm9o4S5JwEd
            client-secret: LZzwxroCa6
            scope:
            - name
            - mobile
            - email
            - birthyear
            - birthday
            - gender
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://springboot-projects.cdawfelgxx1r.ap-northeast-2.rds.amazonaws.com/library_project?useUnicode=true&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: tmdgus7983
    password: jhym6245
mybatis:
  mapper-locations:
  - /mappers/*.xml

file:
  path: C:\song/workspace4/git/springboot-projects/upload/
  
